fix(amd-loader): make another attempt at fixing Windows build
Latest error as seen here:

    https://github.com/liferay/liferay-frontend-projects/pull/198/checks?check_run_id=1275686262

is now:

    Error: ENOENT: no such file or directory, stat 'build\loader\loader-debug.js'
        at Object.statSync (fs.js:1016:3)

which makes me think that our webpack build isn't doing anything on
Windows, because the entry point is wrong, so nothing gets built.

We'll see, anyway.