fix(scripts): use canonical plugin name format
Otherwise we'll throw an error (because we added code to require
canonically formatted names in order to avoid unintended duplicate
plugins when we merge configs).

      Error: checkBabelName(): expected
      "@babel/proposal-export-namespace-from", got
      "@babel/plugin-proposal-export-namespace-from"