fix(guidelines): add missing path declaration to workflow
Attempting to fix:

    > Error: Input required and not supplied: path

    https://github.com/liferay/liferay-frontend-projects/pull/308/checks?check_run_id=1577409877