refactor(changelog-generator): print banner sooner
So that in the `--dry-run` without `--version` use case, you won't see
the "phony version" message before the banner:

```
Using phony version changelog-generator/v0.0.0-placeholder during --dry-run
 ____________________
(_)                  `
  |                  |
  |   changelog.js   |
  |   ============   |
  |                  |
  |   Reporting      |
  |   for duty!      |
  |                  |
  |__________________|
  (_)_________________)

Fetching remote tags: run with --no-update-tags to skip
```

Note that this does mean that we're showing the banner in some
situations where we didn't show it before, but I think that's ok.
Example:

```
changelog-generator ❯ bin/liferay-changelog-generator.js --invalid-option
 ____________________
(_)                  `
  |                  |
  |   changelog.js   |
  |   ============   |
  |                  |
  |   Reporting      |
  |   for duty!      |
  |                  |
  |__________________|
  (_)_________________)

error: Unrecognized argument --invalid-option; see --help for available options
error: Missing required option: --version; see --help for usage
zsh: exit 1     bin/liferay-changelog-generator.js --invalid-option
```