fix: don't silently swallow failures in spawnSync
Test plan: `yarn test` in "liferay-npm-scripts". By way of an
integration test, also do this (which will error out due to a config
clash):

```
../../node_modules/.bin/liferay-npm-scripts test
● Validation Error:

  Configuration options testMatch and testRegex cannot be used together.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

/Users/greghurrell/code/liferay-npm-tools/packages/liferay-npm-scripts/src/utils/spawnSync.js:36
                throw new Error(
                ^

Error: Command jest --config /Users/greghurrell/code/liferay-npm-tools/packages/liferay-npm-scripts/TEMP_jest.config.json exited with code 1
zsh: exit 1     ../../node_modules/.bin/liferay-npm-scripts test
```

Closes: https://github.com/liferay/liferay-npm-tools/issues/38