fix(amd-loader): attempt to get CI passing on Windows
Flying a bit blind here, but trying to get Windows working on CI. Is
currently failing as seen here:

https://github.com/liferay/liferay-frontend-projects/pull/198/checks?check_run_id=1275560442

    Error: ENOENT: no such file or directory, stat 'build/loader/loader-debug.js'
        at Object.statSync (fs.js:1016:3)
        at Object.statSync (D:\a\liferay-frontend-projects\liferay-frontend-projects\node_modules\graceful-fs\polyfills.js:307:34)
        at statSync (D:\a\liferay-frontend-projects\liferay-frontend-projects\node_modules\fs-extra\lib\util\stat.js:10:52)
        at getStatsSync (D:\a\liferay-frontend-projects\liferay-frontend-projects\node_modules\fs-extra\lib\util\stat.js:24:19)
        at Object.checkPathsSync (D:\a\liferay-frontend-projects\liferay-frontend-projects\node_modules\fs-extra\lib\util\stat.js:49:33)
        at Object.copySync (D:\a\liferay-frontend-projects\liferay-frontend-projects\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
        at copy (D:\a\liferay-frontend-projects\liferay-frontend-projects\projects\amd-loader\bin\util.js:11:5)
        at Object.<anonymous> (D:\a\liferay-frontend-projects\liferay-frontend-projects\projects\amd-loader\bin\build-demo.js:16:1)

So I'm going to assume some path shenanigans are at play and can be
cured with a helpful sprinkling of `path.join()` calls. Note that
`globby` expects POSIX paths, so I didn't touch any of those.