chore(senna): update to gulp-metal 2.2.3
Release notes:

    https://github.com/metal/gulp-metal/releases/tag/v2.2.3

Our principal motivation here is to get onto a newer version of
`node-sass` (via a newer version of `gulp-sass`), such that `yarn
install` will actually work.

We've made some progress, because while it doesn't work yet, it gets
further; see the (trimmed) output of `yarn add --dev gulp-metal@latest
--exact`:

    success Saved lockfile.
    success Saved 3 new dependencies.
    info Direct dependencies
    └─ gulp-metal@2.2.3
    info All dependencies
    ├─ ansi-colors@1.1.0
    ├─ gulp-metal@2.2.3
    └─ gulp-sass@4.1.0
    $ gulp && npm run compile
    [18:21:26] Using gulpfile ~/code/liferay-frontend-projects/maintenance/projects/senna/gulpfile.js
    (node:23607) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
    [18:21:26] Starting 'default'...
    [18:21:26] Starting 'clean'...
    [18:21:26] Finished 'clean' after 31 ms
    [18:21:26] Starting 'css'...
    [18:21:26] Finished 'css' after 65 ms
    [18:21:26] Starting 'build:globals'...
    [18:21:26] Starting 'soy'...
    [18:21:26] Finished 'soy' after 4.75 ms
    [18:21:26] Starting 'build:globals:js'...
    The sourceMap option has been renamed to "sourcemap" (lowercase "m") in Rollup. The old form is now deprecated in rollup-stream.
    { message: 'options.entry is deprecated, use options.input' }

    Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
        at validateKeys (/Users/greghurrell/code/liferay-frontend-projects/maintenance/projects/senna/node_modules/rollup/dist/rollup.js:171:11)

So, as you can see, the install basically works, but we have a
post-install script that is trying to do a full build, and blowing up. I
will see what changes I can make to fix that in subsequent commits.