fix(js-toolkit): add prepublishOnly scripts everywhere
We had inconsistent coverage here, which meant that our recent
`@liferay/npm-bundler` release was missing some files. We need
"prepublishOnly" to ensure "build" runs before "publish", because we use
"copyfiles" to copy things like these templates from "src" to "lib":

    src/adapt/templates
    ├── export-module.ejs
    ├── index.js.ejs
    └── manifest-module.ejs

This was manifesting as described here:

    https://github.com/liferay-frontend/liferay-portal/pull/429#issuecomment-708399634

with:

    Error: ENOENT: no such file or directory, open
    'modules/node_modules/@liferay/npm-bundler/lib/adapt/templates/export-module.ejs'

Before this commit we had a variety of set-ups on the js-toolkit
packages:

- generator-js: had "prepublish", which did a build during install as
  well (not what we want, because it generates noise on the `yarn
  install`; everything that gets installed from the npm registry should
  already be complete and ready to go).
- js-toolkit-core: no "prepublish" or "prepublishOnly", which runs the
  risk of making a build without all the necessary files.
- js-toolkit-scripts: "prepublish" instead of "prepublishOnly".
- npm-bridge-generator: same.
- npm-bundler: like js-toolkit-core, no "prepublish" or
  "prepublishOnly".